import type { Theme } from "./types.ts";

export const themes: Theme[] = [
    {
        value: "default",
        label: "Default Dark",
        vars: {
            "--color-bg": "#171614",
            "--color-surface": "#1c1b19",
            "--color-surface-2": "#201f1d",
            "--color-surface-offset": "#252422",
            "--color-surface-dynamic": "#2d2c2a",
            "--color-divider": "#2e2d2b",
            "--color-border": "#393836",
            "--color-text": "#cdccca",
            "--color-text-muted": "#797876",
            "--color-text-faint": "#5a5957",
            "--color-primary": "#4f98a3",
            "--color-primary-hover": "#227f8b",
            "--color-primary-active": "#1a626b",
            "--color-primary-hl": "#1e3436",
            "--color-success": "#6daa45",
            "--color-warning": "#bb653b",
            "--color-error": "#d163a7",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "default-light",
        label: "Default Light",
        vars: {
            "--color-bg": "#f5f4f0",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#eeede9",
            "--color-surface-offset": "#e6e5e1",
            "--color-surface-dynamic": "#dcdbd7",
            "--color-divider": "#d4d3cf",
            "--color-border": "#c4c3bf",
            "--color-text": "#1a1a18",
            "--color-text-muted": "#6b6a68",
            "--color-text-faint": "#9a9997",
            "--color-primary": "#4f98a3",
            "--color-primary-hover": "#3d7a85",
            "--color-primary-active": "#2c5c67",
            "--color-primary-hl": "#d6edf0",
            "--color-success": "#5a9a3a",
            "--color-warning": "#bb653b",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
    {
        value: "midnight",
        label: "Midnight Blue",
        vars: {
            "--color-bg": "#0d1117",
            "--color-surface": "#161b22",
            "--color-surface-2": "#1c2128",
            "--color-surface-offset": "#21262d",
            "--color-surface-dynamic": "#292e36",
            "--color-divider": "#2d323a",
            "--color-border": "#383d45",
            "--color-text": "#c9d1d9",
            "--color-text-muted": "#768390",
            "--color-text-faint": "#545d68",
            "--color-primary": "#58a6ff",
            "--color-primary-hover": "#388bfd",
            "--color-primary-active": "#1f6feb",
            "--color-primary-hl": "#17233b",
            "--color-success": "#3fb950",
            "--color-warning": "#f0883e",
            "--color-error": "#da6d9d",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "midnight-light",
        label: "Midnight Light",
        vars: {
            "--color-bg": "#edf2f7",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#e2e8f0",
            "--color-surface-offset": "#d4dce6",
            "--color-surface-dynamic": "#c8d0da",
            "--color-divider": "#bcc4ce",
            "--color-border": "#acb4be",
            "--color-text": "#1a2332",
            "--color-text-muted": "#5a6b7c",
            "--color-text-faint": "#8a9aaa",
            "--color-primary": "#58a6ff",
            "--color-primary-hover": "#388bfd",
            "--color-primary-active": "#1f6feb",
            "--color-primary-hl": "#d0e4ff",
            "--color-success": "#3fb950",
            "--color-warning": "#f0883e",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
    {
        value: "forest",
        label: "Forest Green",
        vars: {
            "--color-bg": "#161b22",
            "--color-surface": "#1c2128",
            "--color-surface-2": "#21262d",
            "--color-surface-offset": "#262c33",
            "--color-surface-dynamic": "#2e343b",
            "--color-divider": "#32383f",
            "--color-border": "#3d434a",
            "--color-text": "#c9d1d9",
            "--color-text-muted": "#768390",
            "--color-text-faint": "#545d68",
            "--color-primary": "#3fb950",
            "--color-primary-hover": "#2ea043",
            "--color-primary-active": "#238636",
            "--color-primary-hl": "#132b1a",
            "--color-success": "#3fb950",
            "--color-warning": "#d29922",
            "--color-error": "#da6d9d",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "forest-light",
        label: "Forest Light",
        vars: {
            "--color-bg": "#ecf0e7",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#e0e4db",
            "--color-surface-offset": "#d2d6cd",
            "--color-surface-dynamic": "#c4c8bf",
            "--color-divider": "#b8bcb3",
            "--color-border": "#a8aca3",
            "--color-text": "#1a2218",
            "--color-text-muted": "#5a6a58",
            "--color-text-faint": "#8a9a88",
            "--color-primary": "#3fb950",
            "--color-primary-hover": "#2ea043",
            "--color-primary-active": "#238636",
            "--color-primary-hl": "#c8e8ce",
            "--color-success": "#3fb950",
            "--color-warning": "#d29922",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
    {
        value: "ocean",
        label: "Ocean Teal",
        vars: {
            "--color-bg": "#0f172a",
            "--color-surface": "#1e293b",
            "--color-surface-2": "#243044",
            "--color-surface-offset": "#2a364a",
            "--color-surface-dynamic": "#303e54",
            "--color-divider": "#36445a",
            "--color-border": "#415166",
            "--color-text": "#cbd5e1",
            "--color-text-muted": "#7e8ea0",
            "--color-text-faint": "#5c6c7e",
            "--color-primary": "#2dd4bf",
            "--color-primary-hover": "#14b8a6",
            "--color-primary-active": "#0d9488",
            "--color-primary-hl": "#123e3e",
            "--color-success": "#3fb950",
            "--color-warning": "#fb923c",
            "--color-error": "#da6d9d",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "ocean-light",
        label: "Ocean Light",
        vars: {
            "--color-bg": "#e8f0fe",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#dce4f0",
            "--color-surface-offset": "#ced6e2",
            "--color-surface-dynamic": "#c0c8d4",
            "--color-divider": "#b4bcc8",
            "--color-border": "#a4acb8",
            "--color-text": "#0f172a",
            "--color-text-muted": "#4a5a6e",
            "--color-text-faint": "#7a8a9e",
            "--color-primary": "#2dd4bf",
            "--color-primary-hover": "#14b8a6",
            "--color-primary-active": "#0d9488",
            "--color-primary-hl": "#c0f0e8",
            "--color-success": "#3fb950",
            "--color-warning": "#fb923c",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
    {
        value: "royal",
        label: "Royal Purple",
        vars: {
            "--color-bg": "#1a112e",
            "--color-surface": "#2a1a4e",
            "--color-surface-2": "#302056",
            "--color-surface-offset": "#362660",
            "--color-surface-dynamic": "#3e2e6a",
            "--color-divider": "#443474",
            "--color-border": "#504080",
            "--color-text": "#ddd6fe",
            "--color-text-muted": "#9880c4",
            "--color-text-faint": "#705aa0",
            "--color-primary": "#a78bfa",
            "--color-primary-hover": "#8b6ff0",
            "--color-primary-active": "#7c5ce6",
            "--color-primary-hl": "#3d2870",
            "--color-success": "#3fb950",
            "--color-warning": "#f472b6",
            "--color-error": "#da6d9d",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "royal-light",
        label: "Royal Light",
        vars: {
            "--color-bg": "#f0ecf8",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#e4e0f0",
            "--color-surface-offset": "#d6d2e2",
            "--color-surface-dynamic": "#c8c4d4",
            "--color-divider": "#bcb8c8",
            "--color-border": "#aca8b8",
            "--color-text": "#1a112e",
            "--color-text-muted": "#5a4a7a",
            "--color-text-faint": "#8a7aaa",
            "--color-primary": "#a78bfa",
            "--color-primary-hover": "#8b6ff0",
            "--color-primary-active": "#7c5ce6",
            "--color-primary-hl": "#e0d8ff",
            "--color-success": "#3fb950",
            "--color-warning": "#f472b6",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
    {
        value: "slate",
        label: "Slate",
        vars: {
            "--color-bg": "#121316",
            "--color-surface": "#191a1d",
            "--color-surface-2": "#1f2023",
            "--color-surface-offset": "#242528",
            "--color-surface-dynamic": "#2c2d30",
            "--color-divider": "#313234",
            "--color-border": "#3c3d40",
            "--color-text": "#d0d1d4",
            "--color-text-muted": "#7f8084",
            "--color-text-faint": "#5e5f62",
            "--color-primary": "#d4a352",
            "--color-primary-hover": "#c49340",
            "--color-primary-active": "#b08030",
            "--color-primary-hl": "#2a2418",
            "--color-success": "#6daa45",
            "--color-warning": "#bb653b",
            "--color-error": "#d163a7",
            "--color-orange": "#fdab43",
        },
    },
    {
        value: "slate-light",
        label: "Slate Light",
        vars: {
            "--color-bg": "#eef0f2",
            "--color-surface": "#ffffff",
            "--color-surface-2": "#e2e4e6",
            "--color-surface-offset": "#d6d8da",
            "--color-surface-dynamic": "#c8cacc",
            "--color-divider": "#bcbec0",
            "--color-border": "#acaeae",
            "--color-text": "#18191c",
            "--color-text-muted": "#68696c",
            "--color-text-faint": "#989a9c",
            "--color-primary": "#c4903a",
            "--color-primary-hover": "#b08030",
            "--color-primary-active": "#9c7026",
            "--color-primary-hl": "#f0e4cc",
            "--color-success": "#5a9a3a",
            "--color-warning": "#bb653b",
            "--color-error": "#c44a9a",
            "--color-orange": "#e89330",
        },
    },
];

export function applyThemeVars(themeValue: string): void {
    const root = document.documentElement;
    const t = themes.find((x) => x.value === themeValue);
    const defaults = themes[0].vars;
    for (const key of Object.keys(defaults)) {
        root.style.setProperty(key, t ? t.vars[key] ?? defaults[key] : defaults[key]);
    }
}
