name: Deploy Docs

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/docs.yml"
            - "docs/**"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    # Build the VitePress doc site
    build:
        name: Build VitePress Site
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  fetch-depth: 0

            - name: Setup Pages
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

            - name: Setup Node & Bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

            - name: Install Doc Dependencies
              run: bun install --frozen-lockfile --ignore-scripts
              working-directory: docs

            - name: Build VitePress Documentation
              run: bun run docs:build
              working-directory: docs
              env:
                  GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: docs/.vitepress/dist

    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
